# Generated by Django 4.2.4 on 2023-08-28 21:56

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, default='defualt-pic-avater.jpg', null=True, upload_to='upload/category')),
                ('descrption', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1 = hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1 = Trending')),
                ('meta_tilte', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_image', models.ImageField(blank=True, default='cover-book-quran.jpg', null=True, upload_to='upload/profiles')),
                ('descrption', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('profile_cover_image', models.ImageField(blank=True, default='cover-book-quran.jpg', null=True, upload_to='upload/profiles')),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('stats', models.CharField(blank=True, max_length=150, null=True)),
                ('ordered', models.IntegerField(blank=True, null=True)),
                ('conutry', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.CharField(blank=True, max_length=150, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('number_of_books', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_downloaded', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_read', models.IntegerField(blank=True, default=0, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('contat_facebook', models.URLField(blank=True, null=True)),
                ('contat_twitter', models.URLField(blank=True, null=True)),
                ('number_of_gifft', models.IntegerField(default=0)),
                ('aprov', models.BooleanField(default=False)),
                ('pro', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('book_product', models.ImageField(blank=True, null=True, upload_to='upload/products_imags')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upload/thumbnails')),
                ('published_data', models.DateField(auto_now_add=True)),
                ('available', models.CharField(choices=[('publised', 'publised'), ('wiating', 'wiating'), ('draft', 'draft'), ('deleted', 'deleted')], default='wiating', max_length=10)),
                ('number_of_views', models.IntegerField(default=0)),
                ('small_descrption', models.TextField(blank=True, max_length=1000, null=True)),
                ('descrption', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('original_price', models.FloatField(blank=True, default=0, null=True)),
                ('selling_price', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1 = hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1 = Trending')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)])),
                ('tags', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_tilte', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('abrov', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.profile')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='create_by',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='products.profile'),
        ),
    ]
